### ISSUE TITLE
Custom sourcesets no longer have access to main sourceset

### ISSUE THREAD

**Issue by thc202** [eclipse/buildship#701]
This worked fine in the past (don't know which version exactly), it no longer works with `2.2.1.v20180125-1441`. Related to #354?

Import a project with a custom sourceset, say `examples`:
```Gradle
plugins {
    id 'java-library'
}

sourceSets { examples }
```

Notice in the generated `.classpath` that `main` is not used by `examples`:
```XML
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" output="bin/main" path="src/main/java">
		<attributes>
			<attribute name="gradle_scope" value="main"/>
			<attribute name="gradle_used_by_scope" value="main,test"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" output="bin/test" path="src/test/java">
		<attributes>
			<attribute name="gradle_scope" value="test"/>
			<attribute name="gradle_used_by_scope" value="test"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" output="bin/examples" path="src/examples/java">
		<attributes>
			<attribute name="gradle_scope" value="examples"/>
			<attribute name="gradle_used_by_scope" value="examples"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8/"/>
	<classpathentry kind="con" path="org.eclipse.buildship.core.gradleclasspathcontainer"/>
	<classpathentry kind="output" path="bin/default"/>
</classpath>
```

Attempting to run any of the examples from within Eclipse leads to `ClassNotFoundException`:
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/example/SomeClass
	at com.example.SimpleExample.main(SimpleExample.java:7)
Caused by: java.lang.ClassNotFoundException: com.example.SomeClass
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
```

Let me know if more details are needed or if it's better to provide a project.

**Comment by thc202** [comment]
Not an issue, it was missing the wiring of the custom source set:
```Gradle
sourceSets {
    examples {
        compileClasspath += sourceSets.main.output
        runtimeClasspath += output + compileClasspath
    }
}
```
which does generate the expected classpath:
```XML
<classpathentry kind="src" output="bin/main" path="src/main/java">
	<attributes>
		<attribute name="gradle_scope" value="main"/>
		<attribute name="gradle_used_by_scope" value="main,test,examples"/>
	</attributes>
</classpathentry>
```

Sorry for the noise!
